export const industryTypes = {
  en: [
    {
      label: "Agriculture (Agri-business, Farming, etc.)",
      value: "Agriculture",
    },
    {
      label: "Beauty & Wellness",
      value: "Beauty & Wellness",
    },
    { label: "Aviation", value: "Aviation" },
    { label: "Commercial/Retail", value: "Commercial/Retail" },
    { label: "Construction", value: "Construction" },
    { label: "Consulting", value: "Consulting" },
    { label: "Education and Training", value: "Education and Training" },
    {
      label: "Energy/Power Generation",
      value: "Energy/Power Generation",
    },
    { label: "Event Planning", value: "Event Planning" },
    { label: "Fashion", value: "Fashion" },
    { label: "Financial Services", value: "Financial Services" },
    { label: "FMCG", value: "FMCG" },
    { label: "Food & Beverages", value: "Food & Beverages" },
    { label: "Haulage/ Logistics", value: "Haulage/ Logistics" },
    { label: "Healthcare", value: "Healthcare" },
    { label: "ICT", value: "ICT" },
    {
      label: "Intellectual Property Services",
      value: "Intellectual Property Services",
    },
    { label: "Manufacturing", value: "Manufacturing" },
    {
      label: "Media and Entertainment",
      value: "Media and Entertainment",
    },
    { label: "Oil & Gas", value: "Oil & Gas" },
    // { label: "Other", value: "Other" },
    { label: "Professional Services", value: "Professional Services" },
    { label: "Telecommunication", value: "Telecommunication" },
    { label: "Textile", value: "Textile" },
    { label: "Tourism/Hospitality", value: "Tourism/Hospitality" },
    { label: "Transportation", value: "Transportation" },
    { label: "Waste Management", value: "Waste Management" },

    { label: "Legal Services / Law", value: "Legal Services / Law" },
    {
      label: "Forestry and Wood Processing",
      value: "Forestry and Wood Processing",
    },
    { label: "Mining", value: "Mining" },
  ],

  fr: [
    {
      label: "Agriculture (Agri-business, etc.)",
      value: "Agriculture",
    },
    {
      label: "Beauté et bien-être",
      value: "Beauté et bien-être",
    },
    { label: "Aviation", value: "Aviation" },
    { label: "Commerce de détail", value: "Commerce de détail" },
    {
      label:
        "Construction",
      value: "Construction",
    },
    { label: "Consultant", value: "Consultant" },
    {
      label: "Éducation et enseignement",
      value: "Éducation et enseignement",
    },
    {
      label: "Énergie/Production de l'énergie",
      value: "Énergie/Production de l'énergie",
    },
    { label: "Planification d'événements", value: "Planification d'événements" },
    { label: "Mode (coupe couture et stylisme)", value: "Mode (coupe couture et stylisme)" },
    { label: "Services financiers", value: "Services financiers" },
    { label: "Bien de grandes consommation", value: "Bien de grandes consommation" },
    {
      label: "Aliment et boissons",
      value: "Aliment et boissons",
    },
    { label: "Transport et logistique", value: "Transport et logistique" },
    { label: "Soins de santé", value: "Soins de santé" },
    {
      label: "Technologies de l’informatique et de la communication",
      value: "Technologies de l’informatique et de la communication",
    },
    {
      label: "Service de Propriété Intellectuelle",
      value: "Service de Propriété Intellectuelle",
    },
    { label: "Fabrication", value: "Fabrication" },
    {
      label: "Média et divertissement",
      value: "Média et divertissement",
    },
    { label: "Pétrole et gaz", value: "Pétrole et gaz" },
    // { label: "Autre", value: "autre" },
    { label: "Services professionnels", value: "Services professionnels" },
    { label: "Télécommunication", value: "Télécommunication" },
    { label: "Textile", value: "Textile" },
    { label: "Tourisme/Hôtellerie", value: "Tourisme/Hôtellerie" },
    { label: "Transport", value: "Transport" },
    { label: "Gestion des déchets", value: "Gestion des déchets" },
  ],

  pt: [
    {
      label: "Agricultura(Agri-negocio, etc.)",
      value: "Agronegócio",
    },
    {
      label: "Beleza e Bem-Estar",
      value: "Beleza e Bem-Estar",
    },
    { label: "Aviação", value: "Aviação" },
    { label: "Comércio/Retalho ", value: "Comércio/Retalho " },
    { label: "Construção", value: "Construção" },
    { label: "Consultoria", value: "Consulting" },
    { label: "Educação e Treinamento", value: "Educação e Treinament" },
    {
      label: "Geração de Energia/Energia ",
      value: "Geração de Energia/Energia ",
    },
    { label: "Planejamento dos Eventos", value: "Planejamento dos Eventos" },
    { label: "Moda", value: "Fashion" },
    { label: "Serviços financeiros", value: "Serviços financeiros" },
    { label: "Bens de Rápido Consumo ", value: "Bens de Rápido Consumo " },
    { label: "Alimentos e Bebidas", value: "Alimentos e Bebidas" },
    { label: "Transporte/ Logística", value: "Transporte/ Logística" },
    { label: "Cuidados de saúde", value: "Cuidados de saúde " },
    { label: "ICT", value: "ICT" },
    {
      label: "Serviços da Propriedade Intelectuais",
      value: "Serviços da Propriedade Intelectuais",
    },
    { label: "Manufactura", value: "Manufactura" },
    {
      label: "Média e Divertimento",
      value: "Média e Divertimento",
    },
    { label: "Petróleo e Gas", value: "Petróleo e Gas" },
    // { label: "Outros", value: "Outros" },
    { label: "Serviços Profissionais", value: "Serviços Profissionais" },
    { label: "Telecomunicações", value: "Telecomunicações" },
    { label: "Têxtil", value: "Têxtil" },
    { label: "Turismo/Hospitalidade", value: "Turismo/Hospitalidade" },
    { label: "Transportes", value: "Transportes" },
    { label: "Gestão de resíduos", value: "Gestão de resíduos" },
  ],
  
  ar: [
    {
      label: "Agriculture (Agri-business, Farming, etc.)",
      value: "الأعمال التجارية الزراعية",
    },
    {
      label: "Beauty & Wellness",
      value: "مركز التجميل والعافي",
    },
    { label: "Aviation", value: "الطيران" },
    { label: "Commercial/Retail", value: "تجاري/ بيع بالتجزئة " },
    { label: "Construction", value: "البناء" },
    { label: "Consulting", value: "الاستشارة" },
    { label: "Education and Training", value: "التعليم والتدريب" },
    {
      label: "Energy/Power Generation",
      value: "توليد الطاقة/ الطاقة ",
    },
    { label: "Event Planning", value: "تخطيط الأحداث " },
    { label: "Fashion", value: "الموضة" },
    { label: "Financial Services", value: "الخدمات المالية" },
    { label: "FMCG", value: "FMCG" },
    { label: "Food & Beverages", value: "الطعام والمشروبات" },
    { label: "Haulage/ Logistics", value: "السحب/ اللوجستيات" },
    { label: "Healthcare", value: "الرعاية الصحية" },
    { label: "ICT", value: "تكنولوجيا المعلومات والاتصالات" },
    {
      label: "Intellectual Property Services",
      value: "خدمات الملكية الفكرية",
    },
    { label: "Manufacturing", value: "التصنيع" },
    {
      label: "Media and Entertainment",
      value: "وسائل الإعلام والترفيه ",
    },
    { label: "Oil & Gas", value: "النفط والغاز" },
    // { label: "Other", value: "Other" },
    { label: "Professional Services", value: "الخدمات المهنية" },
    { label: "Telecommunication", value: "الاتصالات السلكية واللاسلكية" },
    { label: "Textile", value: "النسيج" },
    { label: "Tourism/Hospitality", value: "السياحة/ الضيافة الإقامة" },
    { label: "Transportation", value: "النقل" },
    { label: "Waste Management", value: "إدارة النفايات" },

    { label: "Legal Services / Law", value: "الخدمات القانونية / القانون" },
    {
      label: "Forestry and Wood Processing",
      value: "الغابات ومعالجة الأخشاب",
    },
    { label: "Mining", value: "صناعة التعدين" },
  ],
};
