export const yearsOfStarupExperience = {
  en: [
    { label: "0-1 year", value: "0-1 year" },
    { label: "1-3 years", value: "1-3 years" },
    { label: "3-5 years", value: "3-5 years" },
    { label: "Over 5 years", value: "over 5 years" },
  ],
  ar: [
    { label: "0-1 year", value: "من 0 إلى 1 سنة." },
    { label: "1-2 years", value: "-13 سنوات." },
    { label: "2-3 years", value: "-3 5 سنوات." },
    { label: "Above 3 years", value: "على مدى 5 سنوات" },
  ],
  pt: [
    { label: "0-1 ano", value: "0-1 ano" },
    { label: "1-2 anos", value: "1-2 anos" },
    { label: "2-3 anos", value: "2-3 anos" },
    { label: "Mais de 5 anos", value: "Mais de 5 anos" },
  ],
  fr: [
    { label: "0-1 année", value: "0-1 année" },
    { label: "1-3 années", value: "1-3 années" },
    { label: "3-5 années", value: "3-5 années" },
    { label: "Plus de 5 années", value: "Plus de 5 années" },
  ],
};

export const experience = {
  en: {
    title: "Applicant's Idea and Experience",
    businessIdea: "Tell us about your business idea ?*",
    businessSummary:
      "Give a little description of your startup idea (or ideas). If you do not have a business idea, then describe an industry or customer problem that you might want to build a business around. (minimum 50 words and maximum 500 words)",
    howManyYears:
      "How many years of business start-up experience do you have (this can be trading or anything)?",
    idea: "Is your idea in your field of experience?",
    yes: "Yes",
    no: "No",
    goals:
      "Which of the United Nations Sustainable Development Goals does your business or idea support (Choose top your top 3)?*",
    businessName: "Business Name*",
    businessLocation: "Buisness Address",
    industry: "In which Industry is your business*",
    subSector: "In which sub-sector is your business*",
    businessCountry: "Business Country*",
    businessState: "What state is your business located*",
    businessCity: "In what city is your business*",
    businessAge: "Age of business?*",
    team: "Are working with a team?*",
    noOfPeople: "How many people are in your team( excluding you)?",
    workHours: "How many hours are you working on your idea per week?*",
    revenue: "Are you currently making some revenue from you idea?*",
    ifYes: "If yes, how much are you currently making per month($)?",
    businessPartners: "Do you have any business partners?*",
    partnerConsent:
      "Do you have your business partner’s consent to take part in this program?",
    partnerConsentLetterUrl: "Upload signed Business Partner Consent letter",
    rural: "Is business in rural area?*",
    requiredInfo: "Please provide the required information",
    select1: "Select",
    select2: "Select, please",
    namePlaceholder: "Enter Business Name",
    continue: "Continue",
    cityPlaceholder: "Type in your city of residence",
  },
  
  ar: {
    title: "فكرة المتقدم وخبرته.",
    businessIdea: "أخبرنا عن فكرة عملك.",
    businessSummary:
      "اذكر وصفاً صغيراً لفكرة بدء التشغيل (أو الأفكار). إذا لم تكن لديك فكرة نهائية عن بدء التشغيل، فقم بوصف مشكلة متعلقة بالصناعة أو العميل قد ترغب في بناء شركة حولها. (50 كلمة كحد أدنى و500 كلمة كحد أقصى)",
    howManyYears:
      "كم سنة من الخبرة في بداية العمل لديك (هذا يمكن أن يكون التداول أو أي شيء)؟.",
    idea: "هل فكرتك أو عملك في مجال خبرتك؟.",
    yes: "نعم",
    no: "/ لا",
    goals:
      "أي من أهداف التنمية المستدامة التي تدعمها شركتك أو فكرتك (اختر من بين أهم 3 أهداف)؟",
    businessName: "اسم العمل.",
    businessLocation: "عنوان عملك",
    industry: "في أي مجال تكون شركتك؟",
    subSector: "قم بالإشارة إلى القطاع الفرعي للصناعة.",
    businessCountry: "موقع بلد العمل / العمل.",
    businessState: "ما هي الحالة التي تقع فيها شركتك؟.",
    businessCity: "في أي مدينة هي عملك؟.",
    businessAge: "عصر الأعمال.",
    team: "هل تعمل مع فريق؟.",
    noOfPeople: "كم عدد الأشخاص الموجودين في فريقك (باستثناء أنت)؟.",
    workHours: "كم ساعة تعمل على فكرتك في الأسبوع؟.",
    revenue: "هل تجِري حاليًا بعض الأرباح من فكرتك؟",
    ifYes: "إذا كانت الإجابة نعم، فما هو المبلغ الذي تقوم بإجلابه حالياً لكل الشهر ($)؟.",
    businessPartners: "هل لديك أي شركاء أعمال؟",
    partnerConsent:
      "هل لديك موافقة شريك عملك على المشاركة في هذا البرنامج؟",
    partnerConsentLetterUrl: "إذا كانت الإجابة "نعم"، فامسح خطاب الموافقة الموقع من قبل شريكك وقم بتحميله.",
    rural: "هل عملك في منطقة ريفية؟",
    requiredInfo: "يرجى تقديم المعلومات المطلوبة",
    select1: "تحديد",
    select2: "الرجاء التحديد",
    namePlaceholder: "أدخل الاسم التجاري",
    continue: "استمر",
    cityPlaceholder: "اكتب في مدينة إقامتك",
  },
  
  fr: {
    partnerConsentLetterUrl:
      "Télécharger la lettre de consentement signée du partenaire commercial",
    title: "Idée et expérience du candidat",
    businessIdea:
      "Parlez-nous de votre idée des affaires ",
    businessSummary:
      "Décrivez brièvement votre idée (ou vos idées) de démarrage. Si vous n'avez pas d'idée finale de démarrage, décrivez un problème de secteur ou de client autour duquel vous voudrez peut-être créer une entreprise. (minimum 50 mots et maximum 500 mots)",
    howManyYears:
      "Combien d'années d'expérience de start-up avez-vous? (ceci peut être une expérience de commerce ou quelque chose d'autres)? ",
    idea:
      "Est-ce que votre idée ou entreprise est dans votre domaine d’expérience? ",
    yes: "Oui",
    no: "Non",
    goals:
      "Lequel des objectifs de développement durable (ODD) des Nations Unies votre entreprise ou idée soutient-elle (mentionnez en haut vos 3 premiers) ",
    businessName: "Nom d'affaire",
    businessLocation: "Localisation de l'affaire",
    industry: "Dans quelle industrie se trouve votre affaire?",
    subSector: "Indiquez votre sous-secteur industrie?*",
    businessCountry: "Pays de l'affaire",
    businessState: "Dans quel Etat se trouve l'affaire?",
    businessCity: "Dans quelle ville se trouve votre affaire?",
    businessAge: "L'âge de l'affaire",
    team: "Travaillez-vous en équipe?*",
    noOfPeople:
      "Combien de personnes compte votre équipe (à l'exclusion de vous)?",
    workHours:
      "Combien d'heures travaillez-vous sur votre idée par semaine?",
    revenue: "Faites-vous actuellement des revenus grâce à votre idée?",
    ifYes:
      "Si oui, combien gagnez-vous actuellement par mois (en $)?",
    businessPartners: "Avez-vous des partenaires d’affaire?",
    partnerConsent:
      "Avez-vous le consentement de votre partenaire d’affaire pour participer à ce programme",
    rural: "L'entreprise est-elle située dans une zone rurale?*",
    requiredInfo: "Fournissez les informations requises",
    select1: "Sélectionnez",
    select2: "Sélectionnez, s'il vous plaît",
    namePlaceholder: "Entrez le nom de l'entreprise",
    continue: "Continuer",
    cityPlaceholder: "Entrer le nom de l'entreprise",
    isInternetStable:
      "Le programme de formation nécessite une connexion internet stable (4G recommandée) pendant une période de 6 semaines. Avez-vous accès à une connexion internet stable (4G), avec votre smartphone, une boîte ADSL ou tout autre équipement",
  },
  pt: {
    partnerConsentLetterUrl:
      "Carregar carta de consentimento de parceiro de negócios assinada",

    title: "Idéia e experiência do candidato",
    businessIdea: "Conte-nos sobre sua ideia de negócio ",
    businessSummary:
      "Dê uma pequena descrição de sua ideia (ou ideias) iniciais. Se você não tem uma ideia final para uma startup, descreva um problema do setor ou do cliente em torno do qual você pode querer construir um negócio. (mínimo de 50 palavras e máximo de 500 palavras)",
    howManyYears:
      "Quantos anos  de experiencia  em abertura de empresas você tem (pode ser vendas ou qualquer coisa)",
    idea: "A sua ideia ou negócio está na sua área de experiência?",
    yes: "Sim",
    no: "Não",
    goals:
      "Qual dos Objetivos de Desenvolvimento Sustentável das Nações Unidas (ODS) seu negócio ou ideia apóia (escolha os 3 principais)? ",
    businessName: "Nome da Empresa",
    businessLocation: "Localização da Empresa",
    industry: "Qual o setor da sua empresa? ",
    subSector: "Indique seu setor industrial",
    businessCountry: "País da Empresa",
    businessState: "Em que estado está a sua empresa localizada?",
    businessCity: "Em que cidade é a sua empresa?",
    businessAge: "Idade de negócio?",
    team: "Você está trabalhando em equipe?",
    noOfPeople: "Quantas pessoas estão em sua equipe (excluindo você)?",
    workHours: "Quantas horas você está trabalhando em sua ideia por semana?",
    revenue: "Atualment você está obtendo alguma receita com sua ideia?",
    ifYes: "Se sim, quanto você está ganhando atualmente por mês (em $)? ",
    businessPartners: "Você tem algum parceiro de negócios?",
    partnerConsent:
      "Você tem o consentimento do seu parceiro de negócios para participar deste programa?",
    rural: "O negócio está em uma área rural? ",
    requiredInfo: "Forneça as informações necessárias",
    select1: "Selecione",
    select2: "Selecione, por favor",
    namePlaceholder: "Insira o nome comercial ",
    continue: "Continue",
    cityPlaceholder: "Digite sua cidade de residência",
  },
};

export const sdgs = {
  en: [
    { value: 1, label: "GOAL 1: No Poverty" },
    { value: 2, label: "GOAL 2: Zero Hunger" },
    { value: 3, label: "GOAL 3: Good Health and Well-being" },
    { value: 4, label: "GOAL 4: Quality Education" },
    { value: 5, label: "GOAL 5: Gender Equality" },
    { value: 6, label: "GOAL 6: Clean Water and Sanitation" },
    { value: 7, label: "GOAL 7: Affordable and Clean Energy" },
    { value: 8, label: "GOAL 8: Decent Work and Economic Growth" },
    {
      value: 9,
      label: "GOAL 9: Industry, Innovation and Infrastructure",
    },
    { value: 10, label: "GOAL 10: Reduced Inequality" },
    { value: 11, label: "GOAL 11: Sustainable Cities and Communities" },
    {
      value: 12,
      label: "GOAL 12: Responsible Consumption and Production",
    },
    { value: 13, label: "GOAL 13: Climate Action" },
    { value: 14, label: "GOAL 14: Life Below Water" },
    { value: 15, label: "GOAL 15: Life on Land" },
    {
      value: 16,
      label: "GOAL 16: Peace and Justice Strong Institutions",
    },
    { value: 17, label: "GOAL 17: Partnerships to achieve the Goal" },
  ],
  ar: [
    { value: 1, label: "الهدف 1: لا فقر." },
    { value: 2, label: "الهدف 2: القضاء على الجوع تماماً." },
    { value: 3, label: "الهدف 3: الصحة الجيدة والرفاهية." },
    { value: 4, label: "الهدف 4: التعليم الجيد." },
    { value: 5, label: "الهدف 5: المساواة بين الجنسين." },
    { value: 6, label: "الهدف 6: المياه النظيفة والمرافق الصحية." },
    { value: 7, label: "الهدف 7: توفير الطاقة النظيفة بأسعار معقولة." },
    { value: 8, label: "الهدف 8: العمل اللائق والنمو الاقتصادي." },
    {
      value: 9,
      label: "الهدف 9: الصناعة والابتكار والبنية التحتية.",
    },
    { value: 10, label: "الهدف 10: الحد من عدم المساواة." },
    { value: 11, label: "الهدف 11: المدن المستدامة والمجتمعات." },
    {
      value: 12,
      label: "الهدف 12: الاستهلاك والإنتاج المسؤولين.",
    },
    { value: 13, label: "الهدف 13: العمل المناخي." },
    { value: 14, label: "الهدف 14: الحياة تحت الماء." },
    { value: 15, label: "الهدف 15: الحياة على الأرض." },
    {
      value: 16,
      label: "الهدف 16: مؤسسات السلام والعدالة القوية.",
    },
    { value: 17, label: "الهدف 17: الشراكات لتحقيق الهدف" },
  ],
  fr: [
    { value: 1, label: "OBJECTIF 1: Éradication de la pauvreté" },
    { value: 2, label: "OBJECTIF 2: Lutte contre la faim" },
    { value: 3, label: "OBJECTIF 3: Bonne santé et bien-être" },
    { value: 4, label: "OBJECTIF 4: Accès à une éducation de qualité" },
    { value: 5, label: "OBJECTIF 5: Égalité entre les sexes" },
    { value: 6, label: "OBJECTIF 6: Accès à l'eau salubre et à l'assainissement " },
    { value: 7, label: "OBJECTIF 7: Énergies fiables, durables et modernes, à un coût 	abordable " },
    {
      value: 8,
      label: "OBJECTIF 8: Accès à des emplois décents ",
    },
    {
      value: 9,
      label: "OBJECTIF 9: Bâtir une infrastructure résiliente, promouvoir une industrialisation durable qui profite à tous et encourager l’innovation",
    },
    { value: 10, label: "OBJECTIF 10: Réduction des inégalités" },
    { value: 11, label: "OBJECTIF 11: Villes et Communautés Durables" },
    {
      value: 12,
      label: "OBJECTIF 12: Consommation et Production Responsables",
    },
    {
      value: 13,
      label: "OBJECTIF 13: Lutte contre les changements climatiques ",
    },
    { value: 14, label: "OBJECTIF 14: Conserver et exploiter de manière durable les océans et les mers aux fins du développement durable" },
    { value: 15, label: "OBJECTIF 15: Vie terrestre" },
    {
      value: 16,
      label: "OBJECTIF 16: Justice et paix",
    },
    {
      value: 17,
      label: "OBJECTIF 17: Partenariats pour la réalisation des objectifs",
    },
  ],
  pt: [
    { value: 1, label: "GOAL 1: Erradicação da Pobreza" },
    { value: 2, label: "GOAL 2: Fome Zero e Agricultura Sustentável" },
    { value: 3, label: "GOAL 3: Saúde e Bem-estar" },
    { value: 4, label: "GOAL 4: Educação de qualidade" },
    { value: 5, label: "GOAL 5:  Igualidade de Gênero" },
    { value: 6, label: "GOAL 6: Água Portável e Saneamento" },
    { value: 7, label: "GOAL 7: Energia Limpa e Accessível" },
    {
      value: 8,
      label: "GOAL 8: Trabalhos Decentes e Crescimento Econômico",
    },
    {
      value: 9,
      label: "GOAL 9: Industria, Inovação e Infraestrutura",
    },
    { value: 10, label: "GOAL 10: Redução das Desigualdades" },
    { value: 11, label: "GOAL 11: Cidades e Comunidades Sustentáveis" },
    {
      value: 12,
      label: "GOAL 12: Consumo e Produção Responsáveis",
    },
    {
      value: 13,
      label: "GOAL 13: Ação Contra A Mudança Global do Clima",
    },
    { value: 14, label: "GOAL 14: Vida na Água" },
    { value: 15, label: "GOAL 15: Vida Terrestre" },
    {
      value: 16,
      label: "GOAL 16: Paz, Justiça e Instituições Eficazes",
    },
    { value: 17, label: "GOAL 17: Parceiras e Meio de Implementação" },
  ],
};

export const subSectors = {
  en: {
    Agriculture: [
      "Livestock Farming",
      "Field Crop Farming",
      "Fishery",
      "Aquaculture",
      "Agroforestry",
      "Agritech",
      "Greenhouse Farming",
    ],
    "Real Estate": ["Residential", "Commercial", "Industrial", "Land"],
    Aviation: [
      "Drone Technology",
      "Air Transport (Freight/ Passenger)",
      "Aircraft Maintenance and Repair Services",
      "Aero Simulation Services",
    ],
    "Beauty & Wellness": [
      "Cosmetics",
      "Makeup Artistry",
      "Spa Services",
      "Nail Technician",
    ],
    "Commercial/Retail": [
      "E-commerce",
      "Supermarket",
      "Grocery Store",
      "Home Furnishing Retailer",
      "Auto Retailer",
    ],
    Construction: [
      "Industrial/ Commercial/ Institutional Building Construction",
      "Water/ Sewer Line Related Structures",
      "Highway/ Street/ Bridge Construction",
      "Other Heavy and Civil Engineering Construction",
      "Flooring Contractor",
      "Masonry Contractor",
      "Painting/ Wall Covering",
      "Tiles Laying",
      "Construction Block Making",
      "Interior Decorator",
    ],
    Consulting: ["Business Consultant", "Legal Services", "Real Estate"],
    "Education and Training": [
      "Online Trainings",
      "Physical Trainings",
      "Educative Games",
      "Awareness Programme",
    ],
    "Energy/Power Generation": [
      "Biodegradable/ Fuel",
      "Coal Consumable Fuel",
      "Solar Energy",
      "Car Battery Retailer",
      "Generator Retailer",
    ],
    "Event Planning": ["Conference/ Summit Convening", "Tradefair Convening"],
    Fashion: [
      "Fashion Designer",
      "Fashion Retailer",
      "Jewelry Retailer",
      "Goldsmith",
      "Fashion Accessories Manufacturer",
    ],
    "Financial Services": ["Fintech", "Banking and Finance"],
    FMCG: ["Toiletries", "Home goods"],
    "Food & Beverages": [
      "Catering",
      "Confectionery",
      "Food Processing",
      "Alcoholic Beverages",
      "Restaurant Business",
    ],
    "Haulage/ Logistics": [
      "Courier Services",
      "Postal Services",
      "Road Haulage",
      "Storage",
      "Warehousing",
    ],
    Healthcare: [
      "Healthtech",
      "Medical Services",
      "Pharmaceuticals",
      "Physician",
      "Medical Practitioner",
    ],
    ICT: [
      "Gaming",
      "Software Developer",
      "Online Platform",
      "Internet Service Provider",
      "Robotics",
      "Artificial Intelligence",
    ],
    "Intellectual Property Services": [
      "Legal Practice",
      "Publisher",
      "Author",
      "Screenplay Writer",
    ],
    Manufacturing: [
      "Woodwork and Furnishing",
      "Food Processing",
      "Hardware Manufacturer",
    ],
    "Media and Entertainment": [
      "Advertising",
      "Audio-visual Technician",
      "Musician",
      "Disk Jockey",
      "Music Producer",
    ],
    "Oil & Gas": [
      "Drilling and Exploration",
      "Transportation",
      "Storage, and Processing",
      "Marketing and Commercial Distribution",
    ],
    "Professional Services": [
      "Accountant",
      "Maintenance Services",
      "Cleaning Services",
      "Security Services",
      "Technician",
      "Plumber",
      "Electrician",
      "Auto Repairs",
    ],
    Telecommunication: [
      "Wireless Communications",
      "Communications Equipment",
      "Processing Systems and Products",
      "Telecommunications Services",
    ],
    Textile: ["Textile Design and Manufacturing", "Textile Wholesale/ Retail"],
    "Tourism/Hospitality": [
      "Travel Service",
      "Adventure Tourism and Recreation",
      "Accommodation",
    ],
    Transportation: [
      "Water transport Services",
      "Road Transport Services",
      "Rail Transport Services",
    ],
    "Waste Management": ["Waste Recycling", "Refuse Collection"],
  },

ar: {
    Agriculture: [
      " تربية الماشية ",
      " زراعة محاصيل الحقل،.",
      " صيد الأسماك،.",
      " الاستزراع المائي.",
      " الغابات الزراعية،.",
      "Agritech",
      " زراعة الدفيئة،.",
    ],
    "Real Estate": ["سكني", "تجاري", "صناعي", "أرض"],
    Aviation: [
      " تقنية الطائرات الصغيرة من دون طيار،",
      "النقل الجوي (الشحن/الركاب)",
      " خدمات صيانة وإصلاح الطائرات،.",
      " خدمات محاكاة Aero.",
    ],
    "Beauty & Wellness": [
      " مستحضرات التجميل",
      " الفن المكياج",
      " خدمات المنتجع الصحي",
      " فني الأظافر",
    ],
    "Commercial/Retail": [
      " التجارة الإلكترونية",
      " سوبر ماركت",
      " محل بقالة",
      " بائع تجزئة للأثاث المنزلي",
      " بائع التجزئة التلقائي",
    ],
    Construction: [
      " بناء المباني الصناعية/التجارية/المؤسسية",
      " الهياكل المتصلة بخط المياه/الصرف الصحي",
      " بناء الطرق السريعة/الشوارع/الجسور",
      " البناء الهندسي الثقيل والمدني",
      " مقاول الأرضيات",
      " مقاول البناء",
      " الطلاء/تغطية الحائط",
      " وضع البلاط",
      "إنشاء كتل الإنشاء،.",
      " مصمم داخلي",
    ],
    Consulting: ["مستشار الأعمال", " الخدمات القانونية", " العقارات"],
    "Education and Training": [
      " تدريبات عبر الإنترنت",
      " التدريبات المادية",
      " الألعاب التعليمية",
      " برامج التوعية",
    ],
    "Energy/Power Generation": [
      " وقود/قابل للتحلل البيولوجي",
      " الوقود المستهلك للفحم",
      " الطاقة الشمسية",
      "بائع تجزئة بطارية السيارة",
      " بائع تجزئة المولد",
    ],
    "Event Planning": ["مؤتمر/مؤتمر القمة", " الدعوة إلى عقد معرض تجاري"],
    Fashion: [
      " مصمم أزياء",
      " بائع الأزياء",
      " بائع المجوهرات",
      " [غلدسميث]",
      " الشركة المصنعة للأكسسوارات العصرية",
    ],
    "Financial Services": [" [فينتيك]", "الخدمات المصرفية والمالية"],
    FMCG: ["أدوات تجميل", " السلع المنزلية"],
    "Food & Beverages": [
      "خدمة توفير الطعام",
      "الحنون",
      "معالجة الطعام",
      "المشروبات الكحولية",
      "مطعم تجارى",
    ],
    "Haulage/ Logistics": [
      "خدمات مندوب التوصيل",
      "الخدمات البريدية",
      "النقل على الطرق",
      "التخزين",
      "التخزين",
    ],
    Healthcare: [
      "صحة تكنولوجيا",
      "الخدمات الطبية",
      "المستحضرات الصيدلانية",
      "الطبيب",
      "ممارس طبي",
    ],
    ICT: [
      "تشغيل الألعاب",
      " مطور البرامج",
      " منصة عبر الإنترنت",
      " موفر خدمة إنترنت",
      "الروبوتات",
      "الذكاء الاصطناعي",
    ],
    "Intellectual Property Services": [
      "الممارسة القانونية",
      "الناشر",
      "الكاتب",
      "كاتب سيناريو",
    ],
    Manufacturing: [
      "الأعمال الخشبية والأثاث",
      "معالجة الغذاء",
      "الشركة المصنعة للأجهزة",
    ],
    "Media and Entertainment": [
      "فنّي الإعلانات",
      "والفني السمعي البصري",
      "والموسيقي",
      "والفارس على الأقراص",
      "ومنتج الموسيقى ",
    ],
    "Oil & Gas": [
      "حفر واستكشاف",
      "النقل",
      "التخزين والمعالجة،",
      "التسويق والتوزيع التجاري",
    ],
    "Professional Services": [
      "محاسب",
      "خدمات الصيانة",
      "خدمات التنظيف",
      "خدمات الأمن",
      "الفني",
      "سباك",
      "كهربائي",
      "الإصلاحات التلقائية",
    ],
    Telecommunication: [
      "الاتصالات اللاسلكية",
      "معدات الاتصالات",
      "أنظمة ومنتجات المعالجة",
      "خدمات الاتصالات السلكية واللاسلكية",
    ],
    Textile: ["تصميم وتصنيع المنسوجات", " المنسوجات بالجملة / التجزئة"],
    "Tourism/Hospitality": [
      "خدمة السفر",
      " سياحة المغامرة والترفيه",
      "الإقامة",
    ],
    Transportation: [
      "خدمات النقل المائي",
      "خدمات النقل البري",
      "خدمات النقل بالسكك الحديدية",
    ],
    "Waste Management": ["إعادة تدوير النفايات", "جمع القمامة"],
  },

  fr: {
    Agriculture: [
      "Agritech",
      "Agroforesterie",
      "L'aquaculture",
      "Les grandes cultures ",
      "Pêcherie",
      "Agriculture en serre",
      "L'élevage,",
    ],
    "Real Estate": ["Residential", "Commercial", "Industrial", "Land"],
    Aviation: [
      "Services de simulation aérodynamique",
      "ATransport aérien (fret / passager)",
      "Services d'entretien et de réparation d'aéronefs",
      "Technologie des drones",
    ],
    "Beauty & Wellness": [
      "Cosmétique Beauté & Bien-être",
      "Maquillage",
      "Technicien de l'ongle",
      "Services de spa",
    ],
    "Commercial/Retail": [
      "Distributeur automobile",
      "Commerce électronique",
      "Épicerie",
      "Distributeur d'ameublement",
      "Supermarché",
    ],
    Construction: [
      "Fabrication de blocs de construction",
      "Entrepreneur en revêtement de sol",
      "Construction de bâtiments industriels / commerciaux / institutionnels, structures liées aux conduites d'eau / d'égout, construction de routes / rues / ponts",
      "Décorateur d'intérieur",
      "Entrepreneur en maçonnerie",
      "Autres constructions de génie civil et lourd",
      "Peinture / Revêtement mural",
      "Pose de carreaux",
    ],
    Consulting: ["Consultant en entreprise", "Services juridiques", "Immobilier"],
    "Education and Training": [
      "Programmes de sensibilisation",
      "Jeux éducatifs",
      "Formations en ligne",
      "Entraînements physiques",
    ],
    "Energy/Power Generation": [
      "Production d'électricité Biodégradable / carburant",
      "Distributeur de batteries de voiture",
      "Carburant consommable de charbon",
      "Distributeur de générateurs",
      "Énergie solaire,",
    ],
    "Event Planning": [
      "Conférence / Sommet sur la planification d'événements",
      "Convocation du salon",
    ],
    Fashion: [
      "Fabricant d'accessoires de mode",
      "Styliste modéliste",
      "Distributeur de mode",
      "Orfèvre",
      "Distributeur de bijoux",
    ],
    "Financial Services": ["Fintech", "Bancaire et financier"],
    FMCG: ["Produits pour la maison", "Articles de toilette"],
    "Food & Beverages": [
      "Aliments et boissons Boissons alcoolisées",
      "Restauration",
      "Confiserie",
      "Préparation des aliments",
      "Entreprise de restaurations",
    ],
    "Haulage/ Logistics": [
      "Services de transport / logistique",
      "Services postaux",
      "Transport routier",
      "Espace de rangement",
      "Entreposage",
    ],
    Healthcare: [
      "Technologie de la santé",
      "Un médecin",
      "Services médicaux",
      "Médicaments",
      "Médecin",
    ],
    ICT: [
      "Intelligence artificielle",
      "Jeux",
      "Fournisseur de services Internet",
      "Plateforme en ligne",
      "Robotique",
      "Développeur de logiciels",
    ],
    "Intellectual Property Services": [
      "Auteur",
      "Pratique légale",
      "Éditeur",
      "Scénariste",
    ],
    Manufacturing: [
      "Fabrication Transformation alimentaire ",
      "Fabricant de matériel",
      "Menuiserie et ameublement",
    ],
    "Media and Entertainment": [
      "Publicité média et divertissement",
      "Technicien audiovisuel",
      "Musicien",
      "Disque jockey",
      "Producteur de musique",
    ],
    "Oil & Gas": [
      "Forage et exploration pétrolière et gazière",
      "Marketing et distribution commerciale",
      "Stockage et traitement",
      "Transport",
    ],
    "Professional Services": [
      "Comptable des services",
      "Réparation automobile professionnels",
      "Services de nettoyage",
      "Électricien",
      "Services de maintenance",
      "Plombier",
      "Services de sécurité",
      "Technicien",
    ],
    Telecommunication: [
      "Communications equipement",
      "Systèmes de traitement et produits",
      "Services de télécommunications",
      "Communications sans fil",
    ],
    Textile: [
      "Conception et fabrication de textiles",
      "Commerce de gros / détaillant de textile",
    ],
    "Tourism/Hospitality": [
      "Hébergement Tourisme / Hôtellerie",
      "Tourisme d'aventure et loisirs",
      "Service de voyage",
    ],
    Transportation: [
      "Services de transport ferroviaire",
      "Services de transport routier",
      "Services de transport par eau",
    ],
    "Waste Management": ["Gestion des déchets", "Le recyclage des déchets"],
  },

  pt: {
    Agriculture: [
      "Agri-tecnologia",
      "Floresta",
      "Aqua-cultura",
      "Agricultura",
      "Pesca",
      "Cultivo em estufas",
      "Pecuária",
    ],
    "Real Estate": ["Residential", "Commercial", "Industrial", "Land"],
    Aviation: [
      "Serviços de simulação aeronáutica,  ",
      "Transporte Aéreo (carga / passageiro)",
      "Serviços de manutenção e reparo de aeronaves",
      "Tecnologia drone",
    ],
    "Beauty & Wellness": [
      "Cosméticos",
      "Arte da maquiagem",
      "Especialista em Unhas",
      "Serviços de Spa",
    ],
    "Commercial/Retail": [
      "Retalhista de peças de carro",
      "E-comércio",
      "Loja de conviniência",
      "Revendedor de Movéis de casa",
      "Supermercado",
    ],
    Construction: [
      "Fabricação de blocos de construção",
      "Empreiteiro de pisos",
      "Construção de Prédios Industriais / Comerciais / Institucionais, Estruturas Relacionadas a Linhas de Água / Esgoto, Construção de Rodovias / Ruas / Pontes",
      "Decorador de interiores",
      "Empreiteiro de alvenaria",
      "Outras construções pesadas e de engenharia civil",
      "Pintura / revestimento de parede",
      "Colocação de telhas",
    ],
    Consulting: ["Consultor de negócios", "Serviços legais", "Imobiliária"],
    "Education and Training": [
      "Programas de conscientização",
      "Jogos educativos",
      "Treinamentos online",
      "Treinamentos presencias",
    ],
    "Energy/Power Generation": [
      "Combustivel biodegradavel",
      "Vendedor de Bateria de carro",
      "Combustível consumível de carvão",
      "Vendedor de Gerador ",
      "Energia solar",
    ],
    "Event Planning": [
      "Conferência / convocação de cúpula,",
      "Convocação de feiras comerciais",
    ],
    Fashion: [
      "Fabricante de acessórios de moda",
      "Designer de moda",
      "Varejista de moda",
      "Ourives",
      "Retalhista de joias",
    ],
    "Financial Services": ["Fintech", "Banca e finanças"],
    FMCG: ["Bens do Lar", "Artigos de higiene"],
    "Food & Beverages": [
      "Bebidas alcoólicas",
      "Confectionery",
      "Confeitaria",
      "Processamento de Alimento",
      "Negócio de Restauração ",
    ],
    "Haulage/ Logistics": [
      "Serviços de entrega",
      "Serviços postais",
      "Transporte rodoviário",
      "Armazenamento",
      "Armazenagem",
    ],
    Healthcare: [
      "Tecnologia da Saúde",
      "Médico",
      "Serviços médicos",
      "Farmacêutica",
      "Médico",
    ],
    ICT: [
      "Inteligência artificial",
      "Jogos",
      "Provedor de internet",
      "Plataforma online",
      "Robótica",
      "Desenvolvedor de Aplicativos",
    ],
    "Intellectual Property Services": [
      "Advogados",
      "Editora",
      "Autor",
      "Escritor de Roteiros",
    ],
    Manufacturing: [
      "Processamento de comida",
      "Fabricante de hardware",
      "Carpintaria e mobília",
    ],
    "Media and Entertainment": [
      "Publicidade",
      "Técnico audiovisual",
      "Músico",
      "Disk Jockey",
      "Produtor Musical",
    ],
    "Oil & Gas": [
      "Perfuração e Exploração",
      "Marketing e distribuição comercial",
      "Armazenamento e processamento",
      "Transporte",
    ],
    "Professional Services": [
      "Contabilista",
      "Mecânico de Carros ",
      "Serviço de Limpeza",
      "Eletricista",
      "Serviços de manutenção",
      "Canalização ",
      "Serviços de segurança",
      "Técnico",
    ],
    Telecommunication: [
      "Equipamentos de Telecomunicação",
      "Sistemas e produtos de processamento",
      "Serviços de telecomunicações",
      "Telecomunicação Wireless/ sem fio",
    ],
    Textile: [
      "Design e fabricação de Têxtil",
      "Retalhista e Grossista de Têxtil",
    ],
    "Tourism/Hospitality": [
      "Acomodação",
      "Turismo de aventura e recreação",
      "Serviço de viagem",
    ],
    Transportation: [
      "Serviços de transporte ferroviário",
      "Serviços de transporte rodoviário",
      "Serviços de transporte aquático",
    ],
    "Waste Management": ["Recuse a coleta", "Reciclagem de lixo"],
  },
};
