export const yearsOfStarupExperience = {
  en: [
    { label: "0-1 year", value: "0-1 year" },
    { label: "1-2 years", value: "1-2 years" },
    { label: "2-3 years", value: "2-3 years" },
    { label: "Above 3 years", value: "above 3 years" },
  ],
  ar: [
    { label: "0-1 year", value: "0-1 year" },
    { label: "1-2 years", value: "1-2 years" },
    { label: "2-3 years", value: "2-3 years" },
    { label: "Above 3 years", value: "above 3 years" },
  ],
  pt: [
    { label: "ano", value: "ano" },
    { label: "1-2 anos", value: "1-2 anos" },
    { label: "2-3 anos", value: "2-3 anos" },
    { label: "plus de 3 anos", value: "plus de 3 anos" },
  ],
  fr: [
    { label: "0-1 an", value: "0-1 an" },
    { label: "1-3 ans", value: "1-3 ans" },
    { label: "3-5 ans", value: "3-5 ans" },
    { label: "Sur 5 ans", value: "Sur 5 ans" },
  ],
};

export const experience = {
  en: {
    title: "Applicant's Idea and Experience",
    businessIdea: "Tell us about your business idea ?*",
    businessSummary:
      "Give a little description of your startup idea (or ideas). If you do not have a business idea, then describe an industry or customer problem that you might want to build a business around. (minimum 50 words and maximum 500 words)",
    howManyYears:
      "How many years of business start-up experience do you have (this can be trading or anything)?",
    idea: "Is your idea in your field of experience?",
    yes: "Yes",
    no: "No",
    goals:
      "Which of the United Nations Sustainable Development Goals does your business or idea support (Choose top your top 3)?*",
    businessName: "Business Name*",
    businessLocation: "Buisness Address",
    industry: "In which Industry is your business*",
    subSector: "In which sub-sector is your business*",
    businessCountry: "Business Country*",
    businessState: "What state is your business located*",
    businessCity: "In what city is your business*",
    businessAge: "Age of business?*",
    team: "Are working with a team?*",
    noOfPeople: "How many people are in your team( excluding you)?",
    workHours: "How many hours are you working on your idea per week?*",
    revenue: "Are you currently making some revenue from you idea?*",
    ifYes: "If yes, how much are you currently making per month($)?",
    businessPartners: "Do you have any business partners?*",
    partnerConsent:
      "Do you have your business partner’s consent to take part in this program?",
    partnerConsentLetterUrl: "Upload signed Business Partner Consent letter",
    rural: "Is business in rural area?*",
    requiredInfo: "Please provide the required information",
    select1: "Select",
    select2: "Select, please",
    namePlaceholder: "Enter Business Name",
    continue: "Continue",
    cityPlaceholder: "Type in your city of residence",
  },
  
  ar: {
    title: "Applicant's Idea and Experience",
    businessIdea: "Tell us about your business idea ?*",
    businessSummary:
      "Give a little description of your startup idea (or ideas). If you do not have a business idea, then describe an industry or customer problem that you might want to build a business around. (minimum 50 words and maximum 500 words)",
    howManyYears:
      "How many years of business start-up experience do you have (this can be trading or anything)?",
    idea: "Is your idea in your field of experience?",
    yes: "Yes",
    no: "No",
    goals:
      "Which of the United Nations Sustainable Development Goals does your business or idea support (Choose top your top 3)?*",
    businessName: "Business Name*",
    businessLocation: "Buisness Address",
    industry: "In which Industry is your business*",
    subSector: "In which sub-sector is your business*",
    businessCountry: "Business Country*",
    businessState: "What state is your business located*",
    businessCity: "In what city is your business*",
    businessAge: "Age of business?*",
    team: "Are working with a team?*",
    noOfPeople: "How many people are in your team( excluding you)?",
    workHours: "How many hours are you working on your idea per week?*",
    revenue: "Are you currently making some revenue from you idea?*",
    ifYes: "If yes, how much are you currently making per month($)?",
    businessPartners: "Do you have any business partners?*",
    partnerConsent:
      "Do you have your business partner’s consent to take part in this program?",
    partnerConsentLetterUrl: "Upload signed Business Partner Consent letter",
    rural: "Is business in rural area?*",
    requiredInfo: "Please provide the required information",
    select1: "Select",
    select2: "Select, please",
    namePlaceholder: "Enter Business Name",
    continue: "Continue",
    cityPlaceholder: "Type in your city of residence",
  },
  
  fr: {
    partnerConsentLetterUrl:
      "Télécharger la lettre de consentement signée du partenaire commercial",
    title: "DÉTAILS SUR L'ENTREPRISE",
    businessIdea:
      "Donnez une petite description de votre (ou de vos) idée(s) de démarrage. Si vous n'avez pas d'idée de création d'entreprise déjà finalisée, décrivez un problème d’un secteur pertinent ou d’un client potentiel autour duquel vous voudriez créer une entreprise. (Minimum 50 mots et maximum 500 mots)*",
    businessSummary:
      "Donnez un peu de description sur votre idée (idées). Si vous n'avez pas uneidée finale, alors décrivez une industrie ou un problème clientèle que vous voulez résoudre. (minimum de 50 mots et maximum de 500 mots)",
    howManyYears:
      "Combien d'années d'expérience en matière de création d'entreprise avez-vous (cela peut être dansle cadre du commerce ou dans d’autres domaines)",
    idea:
      "Votre idée ou votre entreprise est-elle liée à votre domaine d'expérience?",
    yes: "Oui",
    no: "Non",
    goals:
      "Parmi les objectifs de développement durable ci-dessous (ODDs), lequel votre entreprise ou votre idée soutient-elle (choisir les 3 qui sont soutenus prioritairement par votre entreprise ou votre idée d’entreprise)?*",
    businessName: "Nom de l'entreprise",
    businessLocation: "Localisation de l'entreprise",
    industry: "Dans quel secteur d'activité se situe votre entreprise ?*",
    subSector: "Indiquez votre sous-secteur industriel?*",
    businessCountry: "Pays d'activité*",
    businessState: "Dans quel état se trouve votre entreprise*",
    businessCity: "Dans quelle ville est votre entreprise*",
    businessAge: "Âge de l'entreprise*",
    team: "Travaillez-vous en équipe?*",
    noOfPeople:
      "Combien de personnes font partie de votre équipe (sans compter vous-même) ?",
    workHours:
      "Combien d'heures par semaine travaillez-vous actuellement au sein de votre entreprise ?*",
    revenue: "Tirez-vous actuellement des revenus de votre entreprise ?*",
    ifYes:
      "Si oui, combien gagnez-vous actuellement par mois (en USD ou FCFA) ?",
    businessPartners: "Avez-vous des partenaires commerciaux ?*",
    partnerConsent:
      "Avez-vous l'accord de votre partenaire commercial pour participer à ce programme?",
    rural: "L'entreprise est-elle située dans une zone rurale?*",
    requiredInfo: "Veuillez fournir les informations requises",
    select1: "Sélectionner",
    select2: "Sélectionnez, s'il vous plaît",
    namePlaceholder: "Entrez le nom de l'entreprise",
    continue: "Continuer",
    cityPlaceholder: "Tapez votre ville de résidence",
    isInternetStable:
      "Le programme de formation nécessite une connexion internet stable (4G recommandée) pendant une période de 6 semaines. Avez-vous accès à une connexion internet stable (4G), avec votre smartphone, une boîte ADSL ou tout autre équipement",
  },
  pt: {
    partnerConsentLetterUrl:
      "Carregar carta de consentimento de parceiro de negócios assinada",

    title: "Idéia e experiência do candidato",
    businessIdea: "Primeiro, conte-nos sobre sua ideia de negócio ?*",
    businessSummary:
      "Descreva um pouco a sua idéia (idéias). Se você aínda não têm uma idéia final, descreva uma indústria o um problema do cliente cuja solução pode fornecer com negócio. (mínimo de 50 palavras e máximo de 500 palavras)",
    howManyYears:
      "Quantos anos da experiência dum startup você têm.(esto pode ser qualquer coisa)",
    idea: "Você tem a idéia no campo da sua competência?",
    yes: "Si",
    no: "Não",
    goals:
      "Quais dos Objetivos de Desenvolvimento Sustentável (ODS) apoia a sua idéia (Escolhe o melhor 3)?*",
    businessName: "Qual é o nome da sua empresa? / Nome de negócio",
    businessLocation: "Loco de Negócio",
    industry: "Em qual industria fica o seu negócio*",
    subSector: "Indique o subsetor da sua industria*",
    businessCountry: "País de atividade*",
    businessState: "Qual é a condição do seu negócio?*",
    businessCity: "Em que cidade está a sua empresa?*",
    businessAge: "Idade de negócio?*",
    team: "Você têm uma equipe?*",
    noOfPeople: "Quantas pessoas têm em sua equipe (exceto você)?",
    workHours: "Quantas horas você passa por semana executando a sua idéia?*",
    revenue: "Você está ganhando lucros atualmente?*",
    ifYes: "Se a resposta é si, quanto dinheiro ganha por semana ( em  $)?",
    businessPartners: "Você têm parceiros?*",
    partnerConsent:
      "Você têm recebido o acordo do seu parceiro para participar neste programa?",
    rural: "A empresa está localizada em uma área rural?*",
    requiredInfo: "Forneça as informações necessárias",
    select1: "Selecione",
    select2: "Selecione, por favor",
    namePlaceholder: "Insira o nome da empresa",
    continue: "Continue",
    cityPlaceholder: "Digite sua cidade de residência",
  },
};

export const sdgs = {
  en: [
    { value: 1, label: "GOAL 1: No Poverty" },
    { value: 2, label: "GOAL 2: Zero Hunger" },
    { value: 3, label: "GOAL 3: Good Health and Well-being" },
    { value: 4, label: "GOAL 4: Quality Education" },
    { value: 5, label: "GOAL 5: Gender Equality" },
    { value: 6, label: "GOAL 6: Clean Water and Sanitation" },
    { value: 7, label: "GOAL 7: Affordable and Clean Energy" },
    { value: 8, label: "GOAL 8: Decent Work and Economic Growth" },
    {
      value: 9,
      label: "GOAL 9: Industry, Innovation and Infrastructure",
    },
    { value: 10, label: "GOAL 10: Reduced Inequality" },
    { value: 11, label: "GOAL 11: Sustainable Cities and Communities" },
    {
      value: 12,
      label: "GOAL 12: Responsible Consumption and Production",
    },
    { value: 13, label: "GOAL 13: Climate Action" },
    { value: 14, label: "GOAL 14: Life Below Water" },
    { value: 15, label: "GOAL 15: Life on Land" },
    {
      value: 16,
      label: "GOAL 16: Peace and Justice Strong Institutions",
    },
    { value: 17, label: "GOAL 17: Partnerships to achieve the Goal" },
  ],
  ar: [
    { value: 1, label: "GOAL 1: No Poverty" },
    { value: 2, label: "GOAL 2: Zero Hunger" },
    { value: 3, label: "GOAL 3: Good Health and Well-being" },
    { value: 4, label: "GOAL 4: Quality Education" },
    { value: 5, label: "GOAL 5: Gender Equality" },
    { value: 6, label: "GOAL 6: Clean Water and Sanitation" },
    { value: 7, label: "GOAL 7: Affordable and Clean Energy" },
    { value: 8, label: "GOAL 8: Decent Work and Economic Growth" },
    {
      value: 9,
      label: "GOAL 9: Industry, Innovation and Infrastructure",
    },
    { value: 10, label: "GOAL 10: Reduced Inequality" },
    { value: 11, label: "GOAL 11: Sustainable Cities and Communities" },
    {
      value: 12,
      label: "GOAL 12: Responsible Consumption and Production",
    },
    { value: 13, label: "GOAL 13: Climate Action" },
    { value: 14, label: "GOAL 14: Life Below Water" },
    { value: 15, label: "GOAL 15: Life on Land" },
    {
      value: 16,
      label: "GOAL 16: Peace and Justice Strong Institutions",
    },
    { value: 17, label: "GOAL 17: Partnerships to achieve the Goal" },
  ],
  fr: [
    { value: 1, label: "OBJECTIF 1: Pas de pauvreté" },
    { value: 2, label: "OBJECTIF 2: Faim zero" },
    { value: 3, label: "OBJECTIF 3: Santé et bien-être" },
    { value: 4, label: "OBJECTIF 4: Une éducation de qualité" },
    { value: 5, label: "OBJECTIF 5: Égalité des sexes" },
    { value: 6, label: "OBJECTIF 6: Eau propre et assainissement" },
    { value: 7, label: "OBJECTIF 7: Une énergie propre et abordable " },
    {
      value: 8,
      label: "OBJECTIF 8: Travail décent et croissance économique",
    },
    {
      value: 9,
      label: "OBJECTIF 9: Industrie, Innovation et Infrastructure",
    },
    { value: 10, label: "OBJECTIF 10: Réduction des inégalités" },
    { value: 11, label: "OBJECTIF 11: Villes et Communautés Durables" },
    {
      value: 12,
      label: "OBJECTIF 12: Consommation et Production Responsables",
    },
    {
      value: 13,
      label: "OBJECTIF 13: Action pour le climat",
    },
    { value: 14, label: "OBJECTIF 14: La vie sous l'eau" },
    { value: 15, label: "OBJECTIF 15: La vie sur terre" },
    {
      value: 16,
      label: "OBJECTIF 16: Des institutions de paix et de justice fortes",
    },
    {
      value: 17,
      label: "OBJECTIF 17: Partenariats pour le développement",
    },
  ],
  pt: [
    { value: 1, label: "GOAL 1: Erradicação da Pobreza" },
    { value: 2, label: "GOAL 2: Fome Zero e Agricultura Sustentável" },
    { value: 3, label: "GOAL 3: Saúde e Bem-estar" },
    { value: 4, label: "GOAL 4: Educação de qualidade" },
    { value: 5, label: "GOAL 5:  Igualidade de Gênero" },
    { value: 6, label: "GOAL 6: Água Portável e Saneamento" },
    { value: 7, label: "GOAL 7: Energia Limpa e Accessível" },
    {
      value: 8,
      label: "GOAL 8: Trabalhos Decentes e Crescimento Econômico",
    },
    {
      value: 9,
      label: "GOAL 9: Industria, Inovação e Infraestrutura",
    },
    { value: 10, label: "GOAL 10: Redução das Desigualdades" },
    { value: 11, label: "GOAL 11: Cidades e Comunidades Sustentáveis" },
    {
      value: 12,
      label: "GOAL 12: Consumo e Produção Responsáveis",
    },
    {
      value: 13,
      label: "GOAL 13: Ação Contra A Mudança Global do Clima",
    },
    { value: 14, label: "GOAL 14: Vida na Água" },
    { value: 15, label: "GOAL 15: Vida Terrestre" },
    {
      value: 16,
      label: "GOAL 16: Paz, Justiça e Instituições Eficazes",
    },
    { value: 17, label: "GOAL 17: Parceiras e Meio de Implementação" },
  ],
};

export const subSectors = {
  en: {
    Agriculture: [
      "Livestock Farming",
      "Field Crop Farming",
      "Fishery",
      "Aquaculture",
      "Agroforestry",
      "Agritech",
      "Greenhouse Farming",
    ],
    "Real Estate": ["Residential", "Commercial", "Industrial", "Land"],
    Aviation: [
      "Drone Technology",
      "Air Transport (Freight/ Passenger)",
      "Aircraft Maintenance and Repair Services",
      "Aero Simulation Services",
    ],
    "Beauty & Wellness": [
      "Cosmetics",
      "Makeup Artistry",
      "Spa Services",
      "Nail Technician",
    ],
    "Commercial/Retail": [
      "E-commerce",
      "Supermarket",
      "Grocery Store",
      "Home Furnishing Retailer",
      "Auto Retailer",
    ],
    Construction: [
      "Industrial/ Commercial/ Institutional Building Construction",
      "Water/ Sewer Line Related Structures",
      "Highway/ Street/ Bridge Construction",
      "Other Heavy and Civil Engineering Construction",
      "Flooring Contractor",
      "Masonry Contractor",
      "Painting/ Wall Covering",
      "Tiles Laying",
      "Construction Block Making",
      "Interior Decorator",
    ],
    Consulting: ["Business Consultant", "Legal Services", "Real Estate"],
    "Education and Training": [
      "Online Trainings",
      "Physical Trainings",
      "Educative Games",
      "Awareness Programme",
    ],
    "Energy/Power Generation": [
      "Biodegradable/ Fuel",
      "Coal Consumable Fuel",
      "Solar Energy",
      "Car Battery Retailer",
      "Generator Retailer",
    ],
    "Event Planning": ["Conference/ Summit Convening", "Tradefair Convening"],
    Fashion: [
      "Fashion Designer",
      "Fashion Retailer",
      "Jewelry Retailer",
      "Goldsmith",
      "Fashion Accessories Manufacturer",
    ],
    "Financial Services": ["Fintech", "Banking and Finance"],
    FMCG: ["Toiletries", "Home goods"],
    "Food & Beverages": [
      "Catering",
      "Confectionery",
      "Food Processing",
      "Alcoholic Beverages",
      "Restaurant Business",
    ],
    "Haulage/ Logistics": [
      "Courier Services",
      "Postal Services",
      "Road Haulage",
      "Storage",
      "Warehousing",
    ],
    Healthcare: [
      "Healthtech",
      "Medical Services",
      "Pharmaceuticals",
      "Physician",
      "Medical Practitioner",
    ],
    ICT: [
      "Gaming",
      "Software Developer",
      "Online Platform",
      "Internet Service Provider",
      "Robotics",
      "Artificial Intelligence",
    ],
    "Intellectual Property Services": [
      "Legal Practice",
      "Publisher",
      "Author",
      "Screenplay Writer",
    ],
    Manufacturing: [
      "Woodwork and Furnishing",
      "Food Processing",
      "Hardware Manufacturer",
    ],
    "Media and Entertainment": [
      "Advertising",
      "Audio-visual Technician",
      "Musician",
      "Disk Jockey",
      "Music Producer",
    ],
    "Oil & Gas": [
      "Drilling and Exploration",
      "Transportation",
      "Storage, and Processing",
      "Marketing and Commercial Distribution",
    ],
    "Professional Services": [
      "Accountant",
      "Maintenance Services",
      "Cleaning Services",
      "Security Services",
      "Technician",
      "Plumber",
      "Electrician",
      "Auto Repairs",
    ],
    Telecommunication: [
      "Wireless Communications",
      "Communications Equipment",
      "Processing Systems and Products",
      "Telecommunications Services",
    ],
    Textile: ["Textile Design and Manufacturing", "Textile Wholesale/ Retail"],
    "Tourism/Hospitality": [
      "Travel Service",
      "Adventure Tourism and Recreation",
      "Accommodation",
    ],
    Transportation: [
      "Water transport Services",
      "Road Transport Services",
      "Rail Transport Services",
    ],
    "Waste Management": ["Waste Recycling", "Refuse Collection"],
  },

ar: {
    Agriculture: [
      "Livestock Farming",
      "Field Crop Farming",
      "Fishery",
      "Aquaculture",
      "Agroforestry",
      "Agritech",
      "Greenhouse Farming",
    ],
    "Real Estate": ["Residential", "Commercial", "Industrial", "Land"],
    Aviation: [
      "Drone Technology",
      "Air Transport (Freight/ Passenger)",
      "Aircraft Maintenance and Repair Services",
      "Aero Simulation Services",
    ],
    "Beauty & Wellness": [
      "Cosmetics",
      "Makeup Artistry",
      "Spa Services",
      "Nail Technician",
    ],
    "Commercial/Retail": [
      "E-commerce",
      "Supermarket",
      "Grocery Store",
      "Home Furnishing Retailer",
      "Auto Retailer",
    ],
    Construction: [
      "Industrial/ Commercial/ Institutional Building Construction",
      "Water/ Sewer Line Related Structures",
      "Highway/ Street/ Bridge Construction",
      "Other Heavy and Civil Engineering Construction",
      "Flooring Contractor",
      "Masonry Contractor",
      "Painting/ Wall Covering",
      "Tiles Laying",
      "Construction Block Making",
      "Interior Decorator",
    ],
    Consulting: ["Business Consultant", "Legal Services", "Real Estate"],
    "Education and Training": [
      "Online Trainings",
      "Physical Trainings",
      "Educative Games",
      "Awareness Programme",
    ],
    "Energy/Power Generation": [
      "Biodegradable/ Fuel",
      "Coal Consumable Fuel",
      "Solar Energy",
      "Car Battery Retailer",
      "Generator Retailer",
    ],
    "Event Planning": ["Conference/ Summit Convening", "Tradefair Convening"],
    Fashion: [
      "Fashion Designer",
      "Fashion Retailer",
      "Jewelry Retailer",
      "Goldsmith",
      "Fashion Accessories Manufacturer",
    ],
    "Financial Services": ["Fintech", "Banking and Finance"],
    FMCG: ["Toiletries", "Home goods"],
    "Food & Beverages": [
      "Catering",
      "Confectionery",
      "Food Processing",
      "Alcoholic Beverages",
      "Restaurant Business",
    ],
    "Haulage/ Logistics": [
      "Courier Services",
      "Postal Services",
      "Road Haulage",
      "Storage",
      "Warehousing",
    ],
    Healthcare: [
      "Healthtech",
      "Medical Services",
      "Pharmaceuticals",
      "Physician",
      "Medical Practitioner",
    ],
    ICT: [
      "Gaming",
      "Software Developer",
      "Online Platform",
      "Internet Service Provider",
      "Robotics",
      "Artificial Intelligence",
    ],
    "Intellectual Property Services": [
      "Legal Practice",
      "Publisher",
      "Author",
      "Screenplay Writer",
    ],
    Manufacturing: [
      "Woodwork and Furnishing",
      "Food Processing",
      "Hardware Manufacturer",
    ],
    "Media and Entertainment": [
      "Advertising",
      "Audio-visual Technician",
      "Musician",
      "Disk Jockey",
      "Music Producer",
    ],
    "Oil & Gas": [
      "Drilling and Exploration",
      "Transportation",
      "Storage, and Processing",
      "Marketing and Commercial Distribution",
    ],
    "Professional Services": [
      "Accountant",
      "Maintenance Services",
      "Cleaning Services",
      "Security Services",
      "Technician",
      "Plumber",
      "Electrician",
      "Auto Repairs",
    ],
    Telecommunication: [
      "Wireless Communications",
      "Communications Equipment",
      "Processing Systems and Products",
      "Telecommunications Services",
    ],
    Textile: ["Textile Design and Manufacturing", "Textile Wholesale/ Retail"],
    "Tourism/Hospitality": [
      "Travel Service",
      "Adventure Tourism and Recreation",
      "Accommodation",
    ],
    Transportation: [
      "Water transport Services",
      "Road Transport Services",
      "Rail Transport Services",
    ],
    "Waste Management": ["Waste Recycling", "Refuse Collection"],
  },

  fr: {
    Agriculture: [
      "Agritech",
      "Agroforesterie",
      "L'aquaculture",
      "Grandes cultures",
      "Pêcherie",
      "Agriculture en serre",
      "L'élevage,",
    ],
    "Real Estate": ["Residential", "Commercial", "Industrial", "Land"],
    Aviation: [
      "Services de simulation aérodynamique",
      "ATransport aérien (fret / passager)",
      "Services d'entretien et de réparation d'aéronefs",
      "Technologie des drones",
    ],
    "Beauty & Wellness": [
      "Produits de beauté",
      "Maquillage",
      "Technicien de l'ongle",
      "Services de spa",
    ],
    "Commercial/Retail": [
      "Détaillant automobile",
      "Commerce électronique",
      "Épicerie",
      "Détaillant d'ameublement",
      "Supermarché",
    ],
    Construction: [
      "Fabrication de blocs de construction",
      "Entrepreneur en revêtement de sol",
      "Construction de bâtiments industriels / commerciaux / institutionnels, structures liées aux conduites d'eau / d'égout, construction de routes / rues / ponts",
      "Décorateur d'intérieur",
      "Entrepreneur en maçonnerie",
      "Autres constructions de génie civil et lourd",
      "Peinture / Revêtement mural",
      "Pose de carreaux",
    ],
    Consulting: ["Consultant en affaires", "Services juridiques", "Immobilier"],
    "Education and Training": [
      "Programmes de sensibilisation",
      "Jeux éducatifs",
      "Formations en ligne",
      "Entraînements physiques",
    ],
    "Energy/Power Generation": [
      "Biodégradable / carburant",
      "Détaillant de batteries de voiture",
      "Carburant consommable de charbon",
      "Détaillant de générateurs",
      "Énergie solaire,",
    ],
    "Event Planning": [
      "Convocation de conférence / sommet",
      "Convocation du salon",
    ],
    Fashion: [
      "Fabricant d'accessoires de mode",
      "Styliste modéliste",
      "Détaillant de mode",
      "Orfèvre",
      "Détaillant de bijoux",
    ],
    "Financial Services": ["Fintech", "Bancaire et financier"],
    FMCG: ["Articles pour la maison", "Articles de toilette"],
    "Food & Beverages": [
      "Breuvages alcoolisés",
      "Restauration",
      "Confiserie",
      "Préparation des aliments",
      "Entreprise de restaurations",
    ],
    "Haulage/ Logistics": [
      "Services de messagerie",
      "Services postaux",
      "Transport routier",
      "Espace de rangement",
      "Entreposage",
    ],
    Healthcare: [
      "Technologie de la santé",
      "Un médecin",
      "Services médicaux",
      "Médicaments",
      "Médecin",
    ],
    ICT: [
      "Intelligence artificielle",
      "Jeux",
      "Fournisseur de services Internet",
      "Plateforme en ligne",
      "Robotique",
      "Développeur de logiciels",
    ],
    "Intellectual Property Services": [
      "Auteur",
      "Pratique légale",
      "Éditeur",
      "Scénariste",
    ],
    Manufacturing: [
      "Préparation des aliments",
      "Fabricant de matériel",
      "Menuiserie et ameublement",
    ],
    "Media and Entertainment": [
      "Publicité",
      "Technicien audiovisuel",
      "Musicien",
      "Disque jockey",
      "Producteur de musique",
    ],
    "Oil & Gas": [
      "Forage et exploration",
      "Marketing et distribution commerciale",
      "Stockage et traitement",
      "Transport",
    ],
    "Professional Services": [
      "Comptable",
      "Réparation automobile",
      "Services de nettoyage",
      "Électricien",
      "Services de maintenance",
      "Plombier",
      "Services de sécurité",
      "Technicien",
    ],
    Telecommunication: [
      "Matériel de communication",
      "Systèmes de traitement et produits",
      "Services de télécommunications",
      "Communications sans fil",
    ],
    Textile: [
      "Conception et fabrication de textiles",
      "Commerce de gros / détaillant de textile",
    ],
    "Tourism/Hospitality": [
      "Hébergement",
      "Tourisme d'aventure et loisirs",
      "Service de voyage",
    ],
    Transportation: [
      "Services de transport ferroviaire",
      "Services de transport routier",
      "Services de transport par eau",
    ],
    "Waste Management": ["Collecte des ordures", "Le recyclage des déchets"],
  },

  pt: {
    Agriculture: [
      "Agritech",
      "Agrossilvicultura,",
      "Aquicultura,",
      "Agricultura de campo,",
      "Pesca",
      "Agricultura em estufa",
      "Criação de gado",
    ],
    "Real Estate": ["Residential", "Commercial", "Industrial", "Land"],
    Aviation: [
      "Serviços de simulação aeronáutica,  ",
      "Transporte Aéreo (carga / passageiro)",
      "Serviços de manutenção e reparo de aeronaves",
      "Tecnologia drone",
    ],
    "Beauty & Wellness": [
      "Cosméticos",
      "Arte da maquiagem",
      "Serviços de spa",
      "Manicure",
    ],
    "Commercial/Retail": [
      "Revendedor de automóveis",
      "Comércio eletrônico",
      "Bomboneria",
      "Varejista de móveis domésticos",
      "Supermercado",
    ],
    Construction: [
      "Fabricação de blocos de construção",
      "Empreiteiro de pisos",
      "Construção de Prédios Industriais / Comerciais / Institucionais, Estruturas Relacionadas a Linhas de Água / Esgoto, Construção de Rodovias / Ruas / Pontes",
      "Decorador de interiores",
      "Empreiteiro de alvenaria",
      "Outras construções pesadas e de engenharia civil",
      "Pintura / revestimento de parede",
      "Colocação de telhas",
    ],
    Consulting: ["Consultor de negócios", "Serviços legais", "Imobiliária"],
    "Education and Training": [
      "Programas de conscientização",
      "Jogos educativos",
      "Treinamentos online",
      "Treinamentos físicos",
    ],
    "Energy/Power Generation": [
      "Biodegradável / combustível",
      "Revendedor de baterias de automóveis",
      "Combustível consumível de carvão",
      "Varejista de gerador",
      "Energia solar",
    ],
    "Event Planning": [
      "Conferência / convocação de cúpula,",
      "Convocação de feiras comerciais",
    ],
    Fashion: [
      "Fabricante de acessórios de moda",
      "Designer de moda",
      "Varejista de moda",
      "Ourives",
      "Varejista de joias",
    ],
    "Financial Services": ["Fintech", "Banca e finanças"],
    FMCG: ["Bens do Lar", "Artigos de higiene"],
    "Food & Beverages": [
      "Bebidas alcoólicas",
      "Refeições",
      "Confeitaria",
      "Processamento de comida",
      "Negócio de restaurante",
    ],
    "Haulage/ Logistics": [
      "Serviços de entrega",
      "Serviços postais",
      "Transporte rodoviário",
      "Armazenamento",
      "Armazenagem",
    ],
    Healthcare: [
      "Tecnologia da Saúde",
      "Médico",
      "Serviços médicos",
      "Farmacêutica",
      "Médico",
    ],
    ICT: [
      "Inteligência artificial",
      "Jogos",
      "Provedor de internet",
      "Plataforma online",
      "Robótica",
      "Desenvolvedor de software",
    ],
    "Intellectual Property Services": [
      "Prática legal",
      "Editor",
      "Autor",
      "Roteirista",
    ],
    Manufacturing: [
      "Processamento de comida",
      "Fabricante de hardware",
      "Carpintaria e mobília",
    ],
    "Media and Entertainment": [
      "Publicidade",
      "Técnico audiovisual",
      "Músico",
      "Disk Jockey",
      "Produtor Musical",
    ],
    "Oil & Gas": [
      "Perfuração e Exploração",
      "Marketing e distribuição comercial",
      "Armazenamento e processamento",
      "Transporte",
    ],
    "Professional Services": [
      "Contador",
      "Reparos de automóveis",
      "Serviço de Limpeza",
      "Eletricista",
      "Serviços de manutenção",
      "Encanador",
      "Serviços de segurança",
      "Técnico",
    ],
    Telecommunication: [
      "Equipamentos de comunicação",
      "Sistemas e produtos de processamento",
      "Serviços de telecomunicações",
      "Comunicações sem fio",
    ],
    Textile: [
      "Design e fabricação de têxteis",
      "Atacado / varejista de têxteis",
    ],
    "Tourism/Hospitality": [
      "Alojamento",
      "Turismo de aventura e recreação",
      "Serviço de viagem",
    ],
    Transportation: [
      "Serviços de transporte ferroviário",
      "Serviços de transporte rodoviário",
      "Serviços de transporte aquático",
    ],
    "Waste Management": ["Recuse a coleta", "Reciclagem de lixo"],
  },
};
