export const bioInfo = {
  en: {
    title1: "Personal Details",
    firstname: "First name*",
    lastname: "Last name*",
    middleName: "Middle name",
    gender: "Gender*",
    male: "male",
    female: "female",
    others: "Others",
    birthday: "Date of Birth (DD/MM/YYYY)*",
    phoneNumber: "Phone number*",
    email: "Email Address",
    education: "Highest Level of Education*",
    experience: "Years of work experience*",
    country: "Country*",
    state: "State/Region*",
    city: "City*",
    address: "Address*",
    area: "Are you in a rural Area?*",
    applied: "Have you applied for other grants from other foundations?*",
    yes: "Yes",
    no: "No",
    ifYes: "If yes, name the organization",
    typeOfId: "Type of ID*",
    idNumber: "ID Number",
    idScan: "ID scan*",
    programme: "How did you hear about the TEF programme?*",
    title2: "Next of Kin",
    message1:
      "It’s important to have an alternative contact detail in case you’re unreachable",
    message2:
      "We'll love you to onboard your mentor to the TEF platform to help you grow your business.",
    message3: "We'll not spam them",
    message4:
      "Please obtain your mentor’s permission to share their details on this form before completing this section",
    kinFirstname: "First name",
    kinLastname: "Last name",
    kinMiddlename: "Middle name",
    kinPhoneNumber: "Phone number",
    kinEmail: "Email address",
    title3: "Mentor's Details",
    mentorFirstname: "First name",
    mentorLastname: "Last name",
    mentorMiddlename: "Middle name",
    mentorPhoneNumber: "Phone number",
    mentorEmail: "Email address",
    mentorGender: "Gender",
    continue: "Continue to Business Details",
    requiredInfo: "Please provide the required information",
    orgName: "Enter Organization Name",
    kinFirst: "Enter Next of Kin First Name",
    kinLast: "Enter Next of Kin Last Name",
    kinMiddle: "Enter Next of Kin Middle Name",
    kinemail: "Enter Next of Kin Email",
    menFirst: "Enter Next of Mentor's First Name",
    menLast: "Enter Next of Mentor's Last Name",
    menMid: "Enter Next of Mentor's Middle Name",
    menEmail: "Enter Next of Mentor's Email",
    select1: "Select",
    select2: "Select, please",
    cityPlaceholder: "Type in your city of residence",
    motivation:
      "Please describe briefly what motivates you to participate in the programme and what are your expectations from the programme?*",
  },
  fr: {
    title1: "Informations personnelles",
    firstname: "Prénom*",
    lastname: "Nom de famille*",
    middleName: "Deuxième prénom*",
    gender: "Genre*",
    male: "Mâle",
    female: "Femelle",
    others: "Autres",
    birthday: "Date de naissance (JJ/MM/AAAA)*",
    phoneNumber: "Numéro de téléphone*",
    email: "Courriel/adresse e-mail",
    education: "Niveau d'éducation le plus élevé*",
    experience: "Nombre d’années d'expérience professionnelle?",
    country: "Pays*",
    state: "Région*",
    city: "Ville*",
    address: "Adresse*",
    area: "Êtes-vous en zone rurale?*",
    applied:
      "Avez-vous sollicité d'autres subventions auprès d'autres Fondations?*",
    yes: "Oui",
    no: "Non",
    ifYes:
      "Dans l'affirmative, indiquez le nom de l'organisation ou des organisations auprès desquelles vous avez précédemment soumis une candidature.",
    idNumber: "Numéro d'identification",
    typeOfId: "Type de pièce d'identité à télécharger*",
    idScan:
      "Identité (Télécharger une copie scannée de votre pièce d’identité)*",
    programme:
      "Comment avez-vous entendu parler de la Fondation Tony Elumelu?*",
    title2: "Contact d’urgence",
    message1:
      "Il est important de fournir les coordonnées d’une autre personne dans le cas où vous ne seriez pas joignable",
    message2:
      "Nous serons ravis que vous intégriez votre mentor à la plateforme TEF pour vous aider à développer votre entreprise.",
    message3: "Nous ne les spammerons pas",
    message4:
      "Veuillez obtenir la permission de votre mentor pour partager ses coordonnées sur ce formulaire avant de remplir cette section",
    kinFirstname: "Prénom",
    kinLastname: "Nom de famille",
    kinMiddlename: "Deuxième prénom",
    kinPhoneNumber: "Numéro de téléphone",
    kinEmail: "Courriel/adresse e-mail",
    title3: "Détails Mentor",
    mentorFirstname: "Prénom",
    mentorLastname: "Nom",
    mentorMiddlename: "Surnom",
    mentorPhoneNumber: "Numéro de telephone",
    mentorEmail: "Email",
    mentorGender: "Sexe",
    continue: "Continuer vers les détails de l'entreprise",
    requiredInfo: "Veuillez fournir les informations requises",
    orgName: "Entrez le nom de l'organisation",
    kinFirst: "Entrez le prénom le plus proche parent",
    kinLast: " Entrez le nom de famille le plus proche",
    kinMiddle: "Entrez le deuxième prénom du parent",
    kinemail: "Entrez l'e-mail du plus proche parent",
    menFirst: "Entrez le suivant du prénom du mentor",
    menLast: "Entrez le suivant du nom de famille du mentor",
    menMid: "Entrez le suivant du deuxième prénom du mentor",
    menEmail: "Entrez le suivant de l'e-mail du mentor",
    select1: "Sélectionner",
    select2: "Sélectionnez, s'il vous plaît",
    cityPlaceholder: "Tapez votre ville de résidence",
    motivation:
      "Veuillez décrire brièvement ce qui vous motive à participer au programme et quelles sont vos attentes par rapport*",
  },
  pt: {
    title1: "Os detalhes pessoais",
    firstname: "Nome completo*",
    lastname: "Sobrenome*",
    middleName: "Nome*",
    gender: "Gênero*",
    male: "Masculino",
    female: "Feminino",
    others: "Outros",
    birthday: "Aniversário (DD/MM/YYYY)*",
    phoneNumber: "Número da Casa/ Número da rua*",
    email: "E-mail",
    education: "O mais alto nível da educação*",
    experience: "Quantos anos de trabalho têm?*",
    country: "Município*",
    state: "Estado/ Distrito*",
    city: "Cidade*",
    address: "Móbile*",
    area: "Você está em uma área rural?*",
    applied: "Você já aplicou para as outras subvenções das outras fundações?*",
    yes: "Se/ ",
    no: "Não",
    ifYes:
      "Se a resposta e si, qual é os nomes das organizações cujas já aplicou",
    typeOfId: "Tipo de ID*",
    idNumber: "Número de identidade",
    idScan: "ID (Abaixe uma cópia scanned copy)*",
    programme: "Como entendeu do Programa de TEF?*",
    title2: "Parente mais próximo",
    message1:
      "É importante ter outro detalhe de contato caso você não esteja disponível",
    message2:
      "Ficaremos felizes se você integrar seu mentor à plataforma TEF para ajudá-lo a expandir seus negócios.",
    message3: "Nós não os enviaremos como spam",
    message4:
      "Obtenha permissão de seu mentor para compartilhar suas informações de contato neste formulário antes de preencher esta seção",
    kinFirstname: "Nome completo",
    kinLastname: "Sobrenome",
    kinMiddlename: "Nome",
    kinPhoneNumber: "Mobile",
    kinEmail: "Email",
    title3: "Mentor",
    mentorFirstname: "Nome completo",
    mentorLastname: "Sobrenome",
    mentorMiddlename: "Nome",
    mentorPhoneNumber: "Mobile",
    mentorEmail: "Email",
    mentorGender: "Gênero",
    continue: "Continue para detalhes da empresa",
    requiredInfo: "Forneça as informações necessárias",
    orgName: "Digite o nome da organização",
    kinFirst: "Digite o nome do parente mais próximo",
    kinLast: "Digite o sobrenome do parente mais próximo",
    kinMiddle: "Digite o nome do meio do próximo parente",
    kinemail: "Digite o e-mail de parente próximo",
    menFirst: "Digite o próximo do primeiro nome do mentor",
    menLast: "Digite o próximo sobrenome do mentor",
    menMid: "Digite o próximo nome do meio do mentor",
    menEmail: "Digite o próximo e-mail do mentor",
    select1: "Selecione",
    select2: "Selecione, por favor",
    cityPlaceholder: "Digite sua cidade de residência",
  },
};

export const previewInfo = {
  en: {
    title1: "TEF Application Form",
    title2: "Full Bio Details",
    gender: "Gender",
    birthday: "Date of Birth",
    phoneNumber: "Phone number",
    email: "Email Address",
    education: "Highest Level of Education",
    experience: "Years of work experience",
    country: "Country",
    state: "State",
    city: "City",
    address: "Address",
    area: "Are you in a rural Area?",
    applied: "Have you applied for other grants from other foundations?",
    yes: "Yes",
    no: "No",
    ifYes: "If yes, name the organization",
    typeOfId: "Type of ID",
    idNumber: "ID Number",
    programme: "How did you hear about the TEF programme?",
    title3: "Next of kin",
    kinPhoneNumber: "Next of Kin Phone number",
    kinEmail: "Next of Kin Email",
    title4: "Mentor's Details",
    mentorName: "Name",
    mentorPhoneNumber: "Phone number",
    mentorEmail: "Email address",
  },
  fr: {
    title1: "Formulaire de candidature TEF",
    title2: "Détails bio complets",
    gender: "Genre",
    birthday: "Date de naissance",
    idNumber: "Numéro d'identification",
    phoneNumber: "Numéro de telephone",
    email: "Courriel/adresse e-mail",
    education: "Niveau d'éducation le plus élevé",
    experience: "Nombre d’années d'expérience professionnelle?",
    country: "Pays",
    state: "Région",
    city: "Ville",
    address: "Adresse",
    area: "Êtes-vous en zone rurale?",
    applied:
      "Avez-vous sollicité d'autres subventions auprès d'autres Fondations?",
    yes: "Oui ",
    no: "Non",
    ifYes:
      "Dans l'affirmative, indiquez le nom de l'organisation ou des organisations auprès desquelles vous avez précédemment soumis une candidature.",
    typeOfId: "Type de pièce d'identité à télécharger",
    programme: "Comment avez-vous entendu parler de la Fondation Tony Elumelu?",
    title3: "Contact d’urgence",
    kinPhoneNumber: "Numéro de telephone",
    kinEmail: "Courriel/adresse e-mail",
    title4: "Détails Mentor",
    mentorName: "Nom",
    mentorPhoneNumber: "Numéro de telephone",
    mentorEmail: "Email",
    motivation:
      "Veuillez décrire brièvement ce qui vous motive à participer au programme et quelles sont vos attentes par rapport",
  },
  pt: {
    title1: "TEF Application Form",
    title2: "Full Bio Details",
    gender: "Gênero",
    birthday: "Aniversário",
    phoneNumber: "Número da Cas",
    email: "E-mail",
    education: "O mais alto nível da educação",
    experience: "Quantos anos de trabalho têm?",
    country: "Município*",
    state: "Estado",
    idNumber: "Número de identidade",

    city: "Cidade",
    address: "Móbile",
    area: "Você está em uma área rural?",
    applied: "Você já aplicou para as outras subvenções das outras fundações?",
    yes: "Se/ ",
    no: "Não",
    ifYes:
      "Se a resposta e si, qual é os nomes das organizações cujas já aplicou",
    typeOfId: "Tipo de ID",
    programme: "Como entendeu do Programa de TEF?",
    title3: "Parente mais próximo",
    kinPhoneNumber: "Mobile",
    kinEmail: "Email",
    title4: "Mentor",
    mentorName: "Nome",
    mentorPhoneNumber: "Mobile",
    mentorEmail: "Email",
  },
};
